### ISSUE TITLE
Exposing 50000-60000 ports on AWS EKS

### ISSUE THREAD

**Issue by Gauleria** [livekit/livekit-helm#110]
Hello, hope you are doing well

I am trying to install livekit on eks(v1.31) unforunately we can't use TURN so i should expose 50000-60000 ports to the internet and i am stuck on this task
Here is my setup:

Dedicated node-group for livekit, which are hosted in public subnets: each node getting public ip on startup and communicate with internet through internet gateway. SG with inbound ports 50000-60000 udp attached to nodes in this nodegroup:

<img width="1414" alt="Снимок экрана 2024-10-27 в 19 56 43" src="https://github.com/user-attachments/assets/71d0d84e-1cbd-480a-b950-bf602299b8b7">

### values.yaml
```yaml
replicaCount: 2

# Refer to https://docs.livekit.io/deploy/kubernetes/ for instructions

livekit:
  rtc:
    tcp_port: 7881
    port_range_start: 50000
    port_range_end: 60000
    use_ice_lite: true
    use_external_ip: true
    stun_servers: []
  redis:
    address: redis:6379
    db: 15
  keys:
    mykey: key
  turn:
    enabled: false

loadBalancer:
  type: alb
  annotations:
    alb.ingress.kubernetes.io/target-type: ip
  tls:
    - hosts:
        - livekit.mydev


autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 60

# resources are set assuming a 8 core instance
resources:
  limits:
    memory: 2048Mi
  requests:
    cpu: 1000m
    memory: 1024Mi

nodeSelector:
  reserved-for: livekit

tolerations:
- key: livekit
  effect: "NoSchedule"
  operator: "Exists"

```

But when i am trying to test traffic  by opening port inside livekit-server pod
```bash
nc -l 3.70.20.251 50001    
```
and then test connection from my laptop
```bash
nc -zv 3.70.20.251 50001            
nc: connectx to 3.70.20.251 port 50001 (tcp) failed: Connection refused
```
where 3.70.20.251 - public ip of node on which livekit pod is hosted
