### ISSUE TITLE
Allow setting custom annotations for Livekit-Server Service

### ISSUE THREAD

**Issue by hori985** [livekit/livekit-helm#121]
Hello, would it be possible to allow setting custom annotations for livekit-server Service inside `values.yaml`?

Maybe add configurable option in `values.yaml`:

```yaml
livekit:
  service:
    annotations:
      annotationName: annotationValue
```

Context: Trying to add external-dns over a Livekit-Server instance and need the ability to add annotations to the service. 😄
