### ISSUE TITLE
Add support to new prometheus settings o service monitor

### ISSUE THREAD

**Issue by Otoru** [livekit/livekit-helm#123]
Now in livekit we can configure it like this:
```
    values:
      livekit:
        port: 7880
        prometheus:
          port: 6789
```
But this doesn't create our service monitor anymore. Can we support this new notation?
