### ISSUE TITLE
TLS spec in Ingress resource not placed under spec.rules scope causing https to be misconfigured after deployment

### ISSUE THREAD

**Issue by patnordstrom** [livekit/livekit-helm#73]
When deploying the helm chart with a `do` loadbalancer type there is an issue with the Ingress deployment and the tls specification is not present.  The issue seems to be that ingress.spec.tls is missing after the deployment.  It is present in the helm template output but is scoped to the wrong location in the YAML.

How to reproduce:

1. Add the livekit helm repo
2. Copy the contents of this file down locally so you can use it with helm https://github.com/livekit/livekit-helm/blob/master/examples/server-do.yaml
3. Run the command `helm template livekit-deployment livekit/livekit-server --namespace lkns --values server-do.yaml > helm-template-server-do.yaml`
4. This will output a template file with the YAML components
5. Find the Ingress resource and you will see that the tls configuration is scoped to spec.rules[0].tls but to be valid it should be scoped to spec.tls.  When you actually configure the values.yaml file using this example with real data (replacing the placeholder values) it causes tls settings to not be configured for the ingress.  The current workaround is to reapply the ingress manually with the tls spec in the right location.  

Here is the example output from the above:
```
# Source: livekit-server/templates/ingress.yaml
kind: Ingress
metadata:
  name: livekit-deployment-livekit-server
  labels:
    helm.sh/chart: livekit-server-1.4.2
    app.kubernetes.io/name: livekit-server
    app.kubernetes.io/instance: livekit-deployment
    app.kubernetes.io/version: "v1.4.2"
    app.kubernetes.io/managed-by: Helm
  annotations:
  # custom annotations
  # AWS ALB
  # GKE with managed certs
  # DO with cert manager
    cert-manager.io/cluster-issuer: letsencrypt-prod
apiVersion: networking.k8s.io/v1
spec:
  ingressClassName: nginx
  rules:
  # In order to work with cert manager on DO, we cannot set us as a default backend
  - host: "<your-primary-domain>"
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: livekit-deployment-livekit-server
            port:
              number: 80
    tls:
      - hosts:
          - "<your-primary-domain>"
        secretName: "<secret-name>"
```

Here is the change that needs to be manually made to the specification for it to work correctly:
```
# Source: livekit-server/templates/ingress.yaml
kind: Ingress
metadata:
  name: livekit-deployment-livekit-server
  labels:
    helm.sh/chart: livekit-server-1.4.2
    app.kubernetes.io/name: livekit-server
    app.kubernetes.io/instance: livekit-deployment
    app.kubernetes.io/version: "v1.4.2"
    app.kubernetes.io/managed-by: Helm
  annotations:
  # custom annotations
  # AWS ALB
  # GKE with managed certs
  # DO with cert manager
    cert-manager.io/cluster-issuer: letsencrypt-prod
apiVersion: networking.k8s.io/v1
spec:
  ingressClassName: nginx
  rules:
  # In order to work with cert manager on DO, we cannot set us as a default backend
  - host: "<your-primary-domain>"
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: livekit-deployment-livekit-server
            port:
              number: 80
  tls:
    - hosts:
        - "<your-primary-domain>"
      secretName: "<secret-name>"
```

**Comment by davidzhao** [comment]
thank you @patnordstrom! we'll take a look at fixing this.

**Comment by p4block** [comment]
This issue manifested to me during the helm install phase, also on DigitalOcean. Helm did not continue installing normally, exporting to yaml and fixing the field seems to be a decent workaround though!

```
helm install livekit-dev livekit/livekit-server --namespace default --values livekit-values.yaml 
Error: INSTALLATION FAILED: unable to build kubernetes objects from release manifest: error validating "": error validating data: ValidationError(Ingress.spec.rules[0]): unknown field "tls" in io.k8s.api.networking.v1.IngressRule

**Comment by davidzhao** [comment]
I can't seem to reproduce this. Looking at the [Ingress template](https://github.com/livekit/livekit-helm/blob/master/livekit-server/templates/ingress.yaml#L60), it does show a correct two spaces for indentation. Can you spot anything that might be generating an incorrect indent?

here's the YAML that's produced from my run.

```yaml
# Source: livekit-server/templates/ingress.yaml
kind: Ingress
metadata:
  name: test1-livekit-server
  labels:
    helm.sh/chart: livekit-server-1.4.3
    app.kubernetes.io/name: livekit-server
    app.kubernetes.io/instance: test1
    app.kubernetes.io/version: "v1.4.3"
    app.kubernetes.io/managed-by: Helm
  annotations:
  # custom annotations
  # AWS ALB
  # GKE with managed certs
  # DO with cert manager
    cert-manager.io/cluster-issuer: letsencrypt-prod
apiVersion: networking.k8s.io/v1
spec:
  ingressClassName: nginx
  rules:
  # In order to work with cert manager on DO, we cannot set us as a default backend
  - host: "mydomain.com"
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: test1-livekit-server
            port:
              number: 80
  tls:
    - hosts:
        - "mydomain.com"
      secretName: "dz-livekit"
```
