### ISSUE TITLE
Unable to install with loadBalancer type gke-managed-cert

### ISSUE THREAD

**Issue by chiu1984** [livekit/livekit-helm#76]
I would like to install livekit server on GKE with google managed cert. It is the helm values I used, since I am using google managed cert, I suppose secretName is not required:

```
loadBalancer:
  type: gke-managed-cert
  staticIpName: static-ip
  certificateName: cert
  tls:
    - hosts:
      - livekit.host.com
``` 
`
However, I got the following error on the Ingress after helm install:

```
Error syncing to GCP: error running load balancer syncing routine: error getting secrets for Ingress: secret "" does not exist
```

I tried to comment out the tls setting but now I got another error:

```
Error: INSTALLATION FAILED: Ingress.extensions "livekit-server" is invalid: spec: Invalid value: []networking.IngressRule(nil): either `defaultBackend` or `rules` must be specified
```

Any suggestion?

**Comment by frandemona** [comment]
I was having the same issue, I modified the `ingress.yaml` file of the helm chart

My `values.yaml` looks
```yaml
loadBalancer:
  type: gke-managed-cert
  staticIpName: livekit-cluster-load-balancer
  certificateName: livekit-cluster-managed-certificate
```

And the `ingress.yaml` stayed like this:
```yaml
spec:
  {{- if eq .Values.loadBalancer.type "do" }}
  ingressClassName: nginx
  {{- end }}
  defaultBackend:
    service:
      name: {{ $fullName }}
      port:
        number: {{ $svcPort }}
{{- end }}
```
