### ISSUE TITLE
Adding label to discover service monitor for prometheus.

### ISSUE THREAD

**Issue by Q00** [livekit/livekit-helm#97]
Hi. I deployed livekit using eks and configured monitoring. 
But there was an issue between Prometheus and service monitor. Prometheus can not find the service monitor.
Prometheus check a label which is 'release=prometheus' in the service monitor.
But livekit-server helm chart doesn't make this label. 
Please check this [helpers code](https://github.com/livekit/livekit-helm/blob/72e49b301c6663ec4c63c79476489c1082eede28/livekit-server/templates/_helpers.tpl#L36) in livekit-helm repository.

 I edited service monitor and added the line with `release=prometheus` and then Prometheus can find the service monitor.

<img width="437" alt="image" src="https://github.com/livekit/livekit-helm/assets/31264094/3168ebe4-dc7f-4326-8257-4947b3a7ca64">

<img width="1146" alt="image" src="https://github.com/livekit/livekit-helm/assets/31264094/3da1e625-b9df-469c-bcf2-94f6849de5da">

Can I make the PR which add line  'release=prometheus' in service monitor labels if `prometheus_port` is specified in values.yml?

I used this options.
```
replicaCount: 2

# Suggested value for gracefully terminate the pod: 5 hours
livekit:
  port: 7880
  log_level: info
  rtc:
    ...
  redis:
    ...
  keys:
    ...
  prometheus_port: 6789
  turn:
    enabled: true
    ...
loadBalancer:
  type: disable

autoscaling:
  ...

resources:
  ...
serviceMonitor:
  create: true
  annotations: {
    "prometheus.io/scrape": "true",
    "prometheus.io/path": "/metrics",
    "prometheus.io/port": "6789"
  }
  name: "prometheus-operator"
  interval: 30s

```

This is my infrastructure
<img width="1099" alt="image" src="https://github.com/livekit/livekit-helm/assets/31264094/2d0b1354-8db1-4368-ba1e-452483809d7d">
